name: Test Uploading Mermaid Diagrams

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Example Diagrams
    runs-on: ubuntu-latest
    steps:
    - uses: miketrebilcock/python-code-visualiser@beta-1
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}